// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mywusjcbyggafuwpcqay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15d3VzamNieWdnYWZ1d3BjcWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjA3NjYsImV4cCI6MjA2MjE5Njc2Nn0.IynvFq1IGYmC5C2usNsWO-k-ePzSA0OK-nIdUeRUFxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);